// Code generated by dagger. DO NOT EDIT.

package main

import (
	"context"
	"encoding/json"
	"fmt"
	"log/slog"
	"os"
	"sort"

	telemetry "github.com/dagger/otel-go"
	"github.com/vektah/gqlparser/v2/gqlerror"
	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/sdk/resource"
	semconv "go.opentelemetry.io/otel/semconv/v1.40.0"
	"go.opentelemetry.io/otel/trace"

	"dagger/dfcad/internal/dagger"

	"github.com/dagger/querybuilder"
)

var dag = dagger.Connect()

func Tracer() trace.Tracer {
	return otel.Tracer("dagger.io/sdk.go")
}

// used for local MarshalJSON implementations
var marshalCtx = context.Background()

// called by main()
func setMarshalContext(ctx context.Context) {
	marshalCtx = ctx
	dagger.SetMarshalContext(ctx)
}

type DaggerObject interface {
	querybuilder.GraphQLMarshaller
	ID(ctx context.Context) (dagger.ID, error)
}

type ExecError = dagger.ExecError

// ptr returns a pointer to the given value.
func ptr[T any](v T) *T {
	return &v
}

// convertSlice converts a slice of one type to a slice of another type using a
// converter function
func convertSlice[I any, O any](in []I, f func(I) O) []O {
	out := make([]O, len(in))
	for i, v := range in {
		out[i] = f(v)
	}
	return out
}

func (r Dfcad) MarshalJSON() ([]byte, error) {
	var concrete struct {
		Source *dagger.Directory
		GitDir *dagger.Directory
	}
	concrete.Source = r.Source
	concrete.GitDir = r.GitDir
	return json.Marshal(&concrete)
}

func (r *Dfcad) UnmarshalJSON(bs []byte) error {
	var concrete struct {
		Source *dagger.Directory
		GitDir *dagger.Directory
	}
	err := json.Unmarshal(bs, &concrete)
	if err != nil {
		return err
	}
	r.Source = concrete.Source
	r.GitDir = concrete.GitDir
	return nil
}

func main() {
	ctx := context.Background()

	// Direct slog to the new stderr. This is only for dev time debugging, and
	// runtime errors/warnings.
	slog.SetDefault(slog.New(slog.NewTextHandler(os.Stderr, &slog.HandlerOptions{
		Level: slog.LevelWarn,
	})))

	if err := dispatch(ctx); err != nil {
		os.Exit(2)
	}
}

func convertError(rerr error) *dagger.Error {
	if gqlErr := findSingleGQLError(rerr); gqlErr != nil {
		dagErr := dag.Error(gqlErr.Message)
		if gqlErr.Extensions != nil {
			keys := make([]string, 0, len(gqlErr.Extensions))
			for k := range gqlErr.Extensions {
				keys = append(keys, k)
			}
			sort.Strings(keys)
			for _, k := range keys {
				val, err := json.Marshal(gqlErr.Extensions[k])
				if err != nil {
					fmt.Println("failed to marshal error value:", err)
				}
				dagErr = dagErr.WithValue(k, dagger.JSON(val))
			}
		}
		return dagErr
	}
	return dag.Error(rerr.Error())
}

func findSingleGQLError(rerr error) *gqlerror.Error {
	switch x := rerr.(type) {
	case *gqlerror.Error:
		return x
	case interface{ Unwrap() []error }:
		return nil
	case interface{ Unwrap() error }:
		return findSingleGQLError(x.Unwrap())
	default:
		return nil
	}
}
func dispatch(ctx context.Context) (rerr error) {
	ctx = telemetry.InitEmbedded(ctx, resource.NewWithAttributes(
		semconv.SchemaURL,
		semconv.ServiceNameKey.String("dagger-go-sdk"),
		// TODO version?
	))
	defer telemetry.Close()

	// A lot of the "work" actually happens when we're marshalling the return
	// value, which entails getting object IDs, which happens in MarshalJSON,
	// which has no ctx argument, so we use this lovely global variable.
	setMarshalContext(ctx)

	fnCall := dag.CurrentFunctionCall()
	defer func() {
		if rerr != nil {
			if err := fnCall.ReturnError(ctx, convertError(rerr)); err != nil {
				fmt.Println("failed to return error:", err, "\noriginal error:", rerr)
			}
		}
	}()

	parentName, err := fnCall.ParentName(ctx)
	if err != nil {
		return fmt.Errorf("get parent name: %w", err)
	}
	fnName, err := fnCall.Name(ctx)
	if err != nil {
		return fmt.Errorf("get fn name: %w", err)
	}
	parentJson, err := fnCall.Parent(ctx)
	if err != nil {
		return fmt.Errorf("get fn parent: %w", err)
	}
	fnArgs, err := fnCall.InputArgs(ctx)
	if err != nil {
		return fmt.Errorf("get fn args: %w", err)
	}

	inputArgs := map[string][]byte{}
	for _, fnArg := range fnArgs {
		argName, err := fnArg.Name(ctx)
		if err != nil {
			return fmt.Errorf("get fn arg name: %w", err)
		}
		argValue, err := fnArg.Value(ctx)
		if err != nil {
			return fmt.Errorf("get fn arg value: %w", err)
		}
		inputArgs[argName] = []byte(argValue)
	}

	result, err := invoke(ctx, []byte(parentJson), parentName, fnName, inputArgs)
	if err != nil {
		return err
	}
	resultBytes, err := json.Marshal(result)
	if err != nil {
		return fmt.Errorf("marshal: %w", err)
	}

	if err := fnCall.ReturnValue(ctx, dagger.JSON(resultBytes)); err != nil {
		return fmt.Errorf("store return value: %w", err)
	}
	return nil
}
func invoke(ctx context.Context, parentJSON []byte, parentName string, fnName string, inputArgs map[string][]byte) (_ any, err error) {
	_ = inputArgs
	switch parentName {
	case "Dfcad":
		switch fnName {
		case "Binary":
			var parent Dfcad
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var platform dagger.Platform
			if inputArgs["platform"] != nil {
				err = json.Unmarshal([]byte(inputArgs["platform"]), &platform)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg platform", err))
				}
			}
			return (*Dfcad).Binary(&parent, ctx, platform)
		case "Ci":
			var parent Dfcad
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return nil, (*Dfcad).Ci(&parent, ctx)
		case "Publish":
			var parent Dfcad
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var publishOn string
			if inputArgs["publishOn"] != nil {
				err = json.Unmarshal([]byte(inputArgs["publishOn"]), &publishOn)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg publishOn", err))
				}
			}
			var registry string
			if inputArgs["registry"] != nil {
				err = json.Unmarshal([]byte(inputArgs["registry"]), &registry)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg registry", err))
				}
			}
			var repository string
			if inputArgs["repository"] != nil {
				err = json.Unmarshal([]byte(inputArgs["repository"]), &repository)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg repository", err))
				}
			}
			var username string
			if inputArgs["username"] != nil {
				err = json.Unmarshal([]byte(inputArgs["username"]), &username)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg username", err))
				}
			}
			var password *dagger.Secret
			if inputArgs["password"] != nil {
				err = json.Unmarshal([]byte(inputArgs["password"]), &password)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg password", err))
				}
			}
			var idTokenRequestUrl string
			if inputArgs["idTokenRequestUrl"] != nil {
				err = json.Unmarshal([]byte(inputArgs["idTokenRequestUrl"]), &idTokenRequestUrl)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg idTokenRequestUrl", err))
				}
			}
			var idTokenRequestToken *dagger.Secret
			if inputArgs["idTokenRequestToken"] != nil {
				err = json.Unmarshal([]byte(inputArgs["idTokenRequestToken"]), &idTokenRequestToken)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg idTokenRequestToken", err))
				}
			}
			return (*Dfcad).Publish(&parent, ctx, publishOn, registry, repository, username, password, idTokenRequestUrl, idTokenRequestToken)
		case "Version":
			var parent Dfcad
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*Dfcad).Version(&parent, ctx)
		case "VersionScheme":
			var parent Dfcad
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return nil, (*Dfcad).VersionScheme(&parent)
		case "":
			var parent Dfcad
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var source *dagger.Directory
			if inputArgs["source"] != nil {
				err = json.Unmarshal([]byte(inputArgs["source"]), &source)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg source", err))
				}
			}
			var gitDir *dagger.Directory
			if inputArgs["gitDir"] != nil {
				err = json.Unmarshal([]byte(inputArgs["gitDir"]), &gitDir)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg gitDir", err))
				}
			}
			return New(source, gitDir), nil
		default:
			return nil, fmt.Errorf("unknown function %s", fnName)
		}
	default:
		return nil, fmt.Errorf("unknown object %s", parentName)
	}
}
