// Code generated by dagger. DO NOT EDIT.

package dagger

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/dagger/querybuilder"
)

// Retrieve the binding value, as type Go
func (r *Binding) AsGo() *Go { // go (https://github.com/z5labs/devex/tree/c10a12007999eb807f68cd9af9000fbaeab159cb/daggerverse/go/main.go#L24)
	q := r.query.Select("asGo")

	return &Go{
		query: q,
	}
}

// Retrieve the binding value, as type GoCi
func (r *Binding) AsGoCi() *GoCi { // go (https://github.com/z5labs/devex/tree/c10a12007999eb807f68cd9af9000fbaeab159cb/daggerverse/go/ci.go#L44)
	q := r.query.Select("asGoCi")

	return &GoCi{
		query: q,
	}
}

// Create or update a binding of type GoCi in the environment
func (r *Env) WithGoCiInput(name string, value *GoCi, description string) *Env { // go (https://github.com/z5labs/devex/tree/c10a12007999eb807f68cd9af9000fbaeab159cb/daggerverse/go/ci.go#L44)
	assertNotNil("value", value)
	q := r.query.Select("withGoCiInput")
	q = q.Arg("name", name)
	q = q.Arg("value", value)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Declare a desired GoCi output to be assigned in the environment
func (r *Env) WithGoCiOutput(name string, description string) *Env { // go (https://github.com/z5labs/devex/tree/c10a12007999eb807f68cd9af9000fbaeab159cb/daggerverse/go/ci.go#L44)
	q := r.query.Select("withGoCiOutput")
	q = q.Arg("name", name)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Create or update a binding of type Go in the environment
func (r *Env) WithGoInput(name string, value *Go, description string) *Env { // go (https://github.com/z5labs/devex/tree/c10a12007999eb807f68cd9af9000fbaeab159cb/daggerverse/go/main.go#L24)
	assertNotNil("value", value)
	q := r.query.Select("withGoInput")
	q = q.Arg("name", name)
	q = q.Arg("value", value)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Declare a desired Go output to be assigned in the environment
func (r *Env) WithGoOutput(name string, description string) *Env { // go (https://github.com/z5labs/devex/tree/c10a12007999eb807f68cd9af9000fbaeab159cb/daggerverse/go/main.go#L24)
	q := r.query.Select("withGoOutput")
	q = q.Arg("name", name)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Go wraps the Go CLI as Dagger functions. Construct via New(); call
// Container() for the prepared base container, or use the per-CLI helpers
// (Build, Test, Vet, ...) which reuse the same backing container.
type Go struct { // go (https://github.com/z5labs/devex/tree/c10a12007999eb807f68cd9af9000fbaeab159cb/daggerverse/go/main.go#L24)
	query *querybuilder.Selection

	env         *string
	fmt         *string
	id          *ID
	modDownload *Void
	modVerify   *Void
	run         *string
	test        *string
	toolVersion *string
	version     *string
	vet         *Void
	work        *string
}

func (r *Go) WithGraphQLQuery(q *querybuilder.Selection) *Go {
	return &Go{
		query: q,
	}
}

// GoBuildOpts contains options for Go.Build
type GoBuildOpts struct {
	//
	// Package(s) to build, in `go build` package-list syntax.
	//
	//
	// Default: "./..."
	Pkg string // go (https://github.com/z5labs/devex/tree/c10a12007999eb807f68cd9af9000fbaeab159cb/daggerverse/go/main.go#L240)
	//
	// Name of the artifact written under /out. Empty means `-o /out/`, which
	// lets go build name each binary after its main package.
	//
	// Named artifactName rather than output because the Dagger CLI reserves
	// `--output/-o` for exporting a call's result: a function parameter
	// called output collides with it, and `dagger call build` then fails to
	// parse its own flags before it runs anything. Ci.WithBuild's
	// binaryName dodges the same collision; this one is not always a binary,
	// because buildmode can make it an archive or a shared library.
	//
	ArtifactName string // go (https://github.com/z5labs/devex/tree/c10a12007999eb807f68cd9af9000fbaeab159cb/daggerverse/go/main.go#L252)
	//
	// Pass -trimpath: strip the build's local file system paths out of the
	// binary, so the output does not depend on where it was compiled.
	//
	Trimpath bool // go (https://github.com/z5labs/devex/tree/c10a12007999eb807f68cd9af9000fbaeab159cb/daggerverse/go/main.go#L257)
	//
	// Pass -ldflags "-s -w": drop the symbol table and the DWARF debug
	// info. Smaller binary, no usable stack symbolization or debugger.
	//
	Strip bool // go (https://github.com/z5labs/devex/tree/c10a12007999eb807f68cd9af9000fbaeab159cb/daggerverse/go/main.go#L262)
	//
	// Link-time variable assignments, each `importpath.Name=value`,
	// rendered as `-ldflags "-X importpath.Name=value"`. This is how a
	// binary learns its own version or commit. Only the first `=` splits
	// name from value, so a value may itself contain `=`. An element with
	// no `=`, or with an empty name, is rejected. The linker silently
	// ignores a stamp naming a variable that does not exist, or one that
	// is not a package-level string.
	//
	Stamps []string // go (https://github.com/z5labs/devex/tree/c10a12007999eb807f68cd9af9000fbaeab159cb/daggerverse/go/main.go#L272)
	//
	// Build tags, passed as `-tags a,b,c`. Selects which `//go:build`
	// files are compiled in.
	//
	Tags []string // go (https://github.com/z5labs/devex/tree/c10a12007999eb807f68cd9af9000fbaeab159cb/daggerverse/go/main.go#L277)
	//
	// Target platform as `GOOS/GOARCH[/variant]`, e.g. "linux/arm64".
	// Sets GOOS and GOARCH for a cross-compile; empty builds for the
	// toolchain container's own platform. Any variant segment is ignored —
	// GOARM/GOAMD64 are left unset.
	//
	Platform string // go (https://github.com/z5labs/devex/tree/c10a12007999eb807f68cd9af9000fbaeab159cb/daggerverse/go/main.go#L284)
	//
	// Set CGO_ENABLED=0. Produces a statically linked binary with no libc
	// dependency, which is what a scratch image needs, at the cost of the
	// cgo-backed net and os/user implementations.
	//
	DisableCgo bool // go (https://github.com/z5labs/devex/tree/c10a12007999eb807f68cd9af9000fbaeab159cb/daggerverse/go/main.go#L290)
	//
	// Pass -race: link Go's data-race detector into the output. The binary
	// then reports racing accesses to stderr as it runs, at roughly 2-20x
	// the CPU and 5-10x the memory of an ordinary build — so this is a
	// binary for an integration test, not one to ship.
	//
	// -race requires cgo, so it cannot be combined with disableCgo (Build
	// rejects that pairing) and it needs a C toolchain for the target: the
	// golang image has one for its own platform, but a cross-compile via
	// platform does not unless the toolchain image provides it.
	//
	Race bool // go (https://github.com/z5labs/devex/tree/c10a12007999eb807f68cd9af9000fbaeab159cb/daggerverse/go/main.go#L302)
	//
	// Pass -buildmode=<mode>: what the linker emits, which for most modes is
	// not an executable. Absent leaves the flag off entirely, so `go build`
	// picks its own default for the target — an executable for a main
	// package, an archive for the rest. See BuildMode for what each member
	// produces.
	//
	Buildmode GoBuildMode // go (https://github.com/z5labs/devex/tree/c10a12007999eb807f68cd9af9000fbaeab159cb/daggerverse/go/main.go#L310)
}

// Build runs `go build` against the supplied source and returns /out as a
// *dagger.Directory. pkg defaults to `./...`; when output is empty, `-o
// /out/` is used so go build picks names per its own rules (one binary per
// main package).
//
// Every flag this function can pass is a named input with its own doc
// comment, so `dagger functions` describes what each one does to the
// output. There is deliberately no raw `flags []string` escape hatch: a bag
// of strings cannot be validated, cannot be documented per flag, and makes
// every caller re-learn the same spellings. Container() is the escape hatch
// for anything not named here — it hands back the prepared container so a
// caller can run whatever `go build` invocation it likes.
func (r *Go) Build(source *Directory, opts ...GoBuildOpts) *Directory { // go (https://github.com/z5labs/devex/tree/c10a12007999eb807f68cd9af9000fbaeab159cb/daggerverse/go/main.go#L234)
	assertNotNil("source", source)
	q := r.query.Select("build")
	for i := len(opts) - 1; i >= 0; i-- {
		// `pkg` optional argument
		if !querybuilder.IsZeroValue(opts[i].Pkg) {
			q = q.Arg("pkg", opts[i].Pkg)
		}
		// `artifactName` optional argument
		if !querybuilder.IsZeroValue(opts[i].ArtifactName) {
			q = q.Arg("artifactName", opts[i].ArtifactName)
		}
		// `trimpath` optional argument
		if !querybuilder.IsZeroValue(opts[i].Trimpath) {
			q = q.Arg("trimpath", opts[i].Trimpath)
		}
		// `strip` optional argument
		if !querybuilder.IsZeroValue(opts[i].Strip) {
			q = q.Arg("strip", opts[i].Strip)
		}
		// `stamps` optional argument
		if !querybuilder.IsZeroValue(opts[i].Stamps) {
			q = q.Arg("stamps", opts[i].Stamps)
		}
		// `tags` optional argument
		if !querybuilder.IsZeroValue(opts[i].Tags) {
			q = q.Arg("tags", opts[i].Tags)
		}
		// `platform` optional argument
		if !querybuilder.IsZeroValue(opts[i].Platform) {
			q = q.Arg("platform", opts[i].Platform)
		}
		// `disableCgo` optional argument
		if !querybuilder.IsZeroValue(opts[i].DisableCgo) {
			q = q.Arg("disableCgo", opts[i].DisableCgo)
		}
		// `race` optional argument
		if !querybuilder.IsZeroValue(opts[i].Race) {
			q = q.Arg("race", opts[i].Race)
		}
		// `buildmode` optional argument
		if !querybuilder.IsZeroValue(opts[i].Buildmode) {
			q = q.Arg("buildmode", opts[i].Buildmode)
		}
	}
	q = q.Arg("source", source)

	return &Directory{
		query: q,
	}
}

// Ci returns a new pipeline builder bound to the supplied source.
func (r *Go) Ci(source *Directory) *GoCi { // go (https://github.com/z5labs/devex/tree/c10a12007999eb807f68cd9af9000fbaeab159cb/daggerverse/go/ci.go#L72)
	assertNotNil("source", source)
	q := r.query.Select("ci")
	q = q.Arg("source", source)

	return &GoCi{
		query: q,
	}
}

// Container returns the prepared base container with go-mod-cache mounted at
// /go/pkg/mod, go-build-cache mounted at /root/.cache/go-build, source
// mounted at /src, and the working directory set to /src. Use this as an
// escape hatch when a Go command isn't covered by the typed helpers.
//
// The toolchain image is golang:<version> where version comes from New() or,
// when New("") was used, from source/go.mod's `go` directive (fallback
// "latest"). The signature takes ctx + returns error because go.mod
// inspection requires async I/O.
func (r *Go) Container(source *Directory) *Container { // go (https://github.com/z5labs/devex/tree/c10a12007999eb807f68cd9af9000fbaeab159cb/daggerverse/go/main.go#L53)
	assertNotNil("source", source)
	q := r.query.Select("container")
	q = q.Arg("source", source)

	return &Container{
		query: q,
	}
}

// CycloneDx renders a CycloneDX 1.6 JSON document describing the module
// graph compiled into binary.
//
// **Why 1.6.** 1.6 is the current release and the one Dependency-Track,
// Grype and Trivy consume; it is also the first to model a component's
// licence acknowledgement, which is what lets a low-confidence classifier
// match be published as "declared" rather than silently asserted.
//
// The component set, the versions and the licences are identical to what
// Spdx emits for the same inputs: both render from one resolution of the
// graph, so the two documents cannot disagree about what shipped. See
// Spdx for how the graph is resolved and how licence confidence is
// handled.
func (r *Go) CycloneDx(binary *File, source *Directory) *File { // go (https://github.com/z5labs/devex/tree/c10a12007999eb807f68cd9af9000fbaeab159cb/daggerverse/go/sbom.go#L80)
	assertNotNil("binary", binary)
	assertNotNil("source", source)
	q := r.query.Select("cycloneDx")
	q = q.Arg("binary", binary)
	q = q.Arg("source", source)

	return &File{
		query: q,
	}
}

// Env runs `go env` in a source-less base container and returns its stdout.
func (r *Go) Env(ctx context.Context) (string, error) { // go (https://github.com/z5labs/devex/tree/c10a12007999eb807f68cd9af9000fbaeab159cb/daggerverse/go/main.go#L488)
	if r.env != nil {
		return *r.env, nil
	}
	q := r.query.Select("env")

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// Fmt runs `gofmt -l -d .` against the supplied source. Returns the diff
// of any unformatted files; non-empty output is also returned as an error so
// CI fails fast on formatting violations.
func (r *Go) Fmt(ctx context.Context, source *Directory) (string, error) { // go (https://github.com/z5labs/devex/tree/c10a12007999eb807f68cd9af9000fbaeab159cb/daggerverse/go/main.go#L452)
	assertNotNil("source", source)
	if r.fmt != nil {
		return *r.fmt, nil
	}
	q := r.query.Select("fmt")
	q = q.Arg("source", source)

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// GoGenerateOpts contains options for Go.Generate
type GoGenerateOpts struct {

	// Default: "./..."
	Pkg string // go (https://github.com/z5labs/devex/tree/c10a12007999eb807f68cd9af9000fbaeab159cb/daggerverse/go/main.go#L191)
}

// Generate runs `go generate pkg` against the supplied source and returns
// /src after generation. pkg defaults to `./...`.
func (r *Go) Generate(source *Directory, opts ...GoGenerateOpts) *Directory { // go (https://github.com/z5labs/devex/tree/c10a12007999eb807f68cd9af9000fbaeab159cb/daggerverse/go/main.go#L187)
	assertNotNil("source", source)
	q := r.query.Select("generate")
	for i := len(opts) - 1; i >= 0; i-- {
		// `pkg` optional argument
		if !querybuilder.IsZeroValue(opts[i].Pkg) {
			q = q.Arg("pkg", opts[i].Pkg)
		}
	}
	q = q.Arg("source", source)

	return &Directory{
		query: q,
	}
}

// A unique identifier for this Go.
func (r *Go) ID(ctx context.Context) (ID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response ID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *Go) XXX_GraphQLType() string {
	return "Go"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *Go) XXX_GraphQLIDType() string {
	return "ID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *Go) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *Go) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *Go) UnmarshalJSON(bs []byte) error {
	var id string
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = Go{query: selectNode(dag.query, id, "Go")}
	return nil
}

// Install runs `go install pkg` in a source-less base container with
// GOBIN=/out and returns the resulting binary as a *dagger.File. The
// returned filename is the basename of pkg (with any @version suffix
// stripped), matching `go install`'s naming rules.
//
// pkg MUST be pinned to an explicit version (e.g. `pkg@v1.2.3` or a
// commit-hash pseudo-version); `@latest` and bare paths are rejected.
// The pin is what makes the result safe to cache across calls within a
// session — without it, the proxy could resolve different versions on
// successive invocations.
func (r *Go) Install(pkg string) *File { // go (https://github.com/z5labs/devex/tree/c10a12007999eb807f68cd9af9000fbaeab159cb/daggerverse/go/main.go#L84)
	q := r.query.Select("install")
	q = q.Arg("pkg", pkg)

	return &File{
		query: q,
	}
}

// ModDownload runs `go mod download` against the supplied source.
func (r *Go) ModDownload(ctx context.Context, source *Directory) error { // go (https://github.com/z5labs/devex/tree/c10a12007999eb807f68cd9af9000fbaeab159cb/daggerverse/go/main.go#L162)
	assertNotNil("source", source)
	if r.modDownload != nil {
		return nil
	}
	q := r.query.Select("modDownload")
	q = q.Arg("source", source)

	return q.Execute(ctx)
}

// ModTidy runs `go mod tidy` against the supplied source and returns the
// updated /src directory.
func (r *Go) ModTidy(source *Directory) *Directory { // go (https://github.com/z5labs/devex/tree/c10a12007999eb807f68cd9af9000fbaeab159cb/daggerverse/go/main.go#L148)
	assertNotNil("source", source)
	q := r.query.Select("modTidy")
	q = q.Arg("source", source)

	return &Directory{
		query: q,
	}
}

// ModVerify runs `go mod verify` against the supplied source.
func (r *Go) ModVerify(ctx context.Context, source *Directory) error { // go (https://github.com/z5labs/devex/tree/c10a12007999eb807f68cd9af9000fbaeab159cb/daggerverse/go/main.go#L174)
	assertNotNil("source", source)
	if r.modVerify != nil {
		return nil
	}
	q := r.query.Select("modVerify")
	q = q.Arg("source", source)

	return q.Execute(ctx)
}

// GoRunOpts contains options for Go.Run
type GoRunOpts struct {
	Args []string // go (https://github.com/z5labs/devex/tree/c10a12007999eb807f68cd9af9000fbaeab159cb/daggerverse/go/main.go#L209)
}

// Run runs `go run pkg [args...]` against the supplied source and returns
// the program's stdout. pkg is required (a single runnable main package).
func (r *Go) Run(ctx context.Context, source *Directory, pkg string, opts ...GoRunOpts) (string, error) { // go (https://github.com/z5labs/devex/tree/c10a12007999eb807f68cd9af9000fbaeab159cb/daggerverse/go/main.go#L204)
	assertNotNil("source", source)
	if r.run != nil {
		return *r.run, nil
	}
	q := r.query.Select("run")
	for i := len(opts) - 1; i >= 0; i-- {
		// `args` optional argument
		if !querybuilder.IsZeroValue(opts[i].Args) {
			q = q.Arg("args", opts[i].Args)
		}
	}
	q = q.Arg("source", source)
	q = q.Arg("pkg", pkg)

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// Spdx renders an SPDX 2.3 JSON document describing the module graph
// compiled into binary.
//
// **Why 2.3 and not 3.0.** The version is chosen for what consumers
// ingest rather than left to whatever the library defaults to. SPDX 2.3
// is the revision behind ISO/IEC 5962's successor line that GitHub's
// dependency graph, Dependency-Track, Grype, Trivy and the CISA/NTIA
// minimum-elements tooling all read today; 3.0 changes the serialization
// wholesale and support for it is still thin. A document nothing can
// parse is not an SBOM.
//
// **The subject is the binary, not the tree.** The component list is read
// out of the compiled artifact with debug/buildinfo, so it names the
// modules that were actually linked in — not everything go.mod happens to
// require. source is an *input* and not the subject: a Go binary embeds
// module paths, versions and hashes but no licence text, so the licences
// have to be resolved from the module cache the source pins.
//
// **Licences are declared and concluded separately.** Licence
// identification is a classifier, and a classifier reports coverage
// rather than a verdict. The classifier's best match is always recorded
// as the declared licence; it is only promoted to the concluded licence
// when the match covers essentially the whole file. Anything less
// concludes NOASSERTION, so a low-confidence match cannot be mistaken
// downstream for an established one.
func (r *Go) Spdx(binary *File, source *Directory) *File { // go (https://github.com/z5labs/devex/tree/c10a12007999eb807f68cd9af9000fbaeab159cb/daggerverse/go/sbom.go#L46)
	assertNotNil("binary", binary)
	assertNotNil("source", source)
	q := r.query.Select("spdx")
	q = q.Arg("binary", binary)
	q = q.Arg("source", source)

	return &File{
		query: q,
	}
}

// GoTestOpts contains options for Go.Test
type GoTestOpts struct {

	// Default: "./..."
	Pkg string // go (https://github.com/z5labs/devex/tree/c10a12007999eb807f68cd9af9000fbaeab159cb/daggerverse/go/main.go#L428)

	Race bool // go (https://github.com/z5labs/devex/tree/c10a12007999eb807f68cd9af9000fbaeab159cb/daggerverse/go/main.go#L430)

	Flags []string // go (https://github.com/z5labs/devex/tree/c10a12007999eb807f68cd9af9000fbaeab159cb/daggerverse/go/main.go#L432)
}

// Test runs `go test -count=1 [-race] [flags] pkg` against the supplied
// source and returns the combined stdout. -count=1 is always passed to
// bypass Go's internal test cache.
func (r *Go) Test(ctx context.Context, source *Directory, opts ...GoTestOpts) (string, error) { // go (https://github.com/z5labs/devex/tree/c10a12007999eb807f68cd9af9000fbaeab159cb/daggerverse/go/main.go#L424)
	assertNotNil("source", source)
	if r.test != nil {
		return *r.test, nil
	}
	q := r.query.Select("test")
	for i := len(opts) - 1; i >= 0; i-- {
		// `pkg` optional argument
		if !querybuilder.IsZeroValue(opts[i].Pkg) {
			q = q.Arg("pkg", opts[i].Pkg)
		}
		// `race` optional argument
		if !querybuilder.IsZeroValue(opts[i].Race) {
			q = q.Arg("race", opts[i].Race)
		}
		// `flags` optional argument
		if !querybuilder.IsZeroValue(opts[i].Flags) {
			q = q.Arg("flags", opts[i].Flags)
		}
	}
	q = q.Arg("source", source)

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// ToolVersion runs `go version` in a source-less base container and returns
// the trimmed output (e.g. "go version go1.23.0 linux/amd64").
func (r *Go) ToolVersion(ctx context.Context) (string, error) { // go (https://github.com/z5labs/devex/tree/c10a12007999eb807f68cd9af9000fbaeab159cb/daggerverse/go/main.go#L496)
	if r.toolVersion != nil {
		return *r.toolVersion, nil
	}
	q := r.query.Select("toolVersion")

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// Version is the pinned Go toolchain version (e.g. "1.23"). Empty
// means infer from the supplied source's go.mod `go` directive;
// falls back to "latest" when no go directive is found.
func (r *Go) Version(ctx context.Context) (string, error) { // go (https://github.com/z5labs/devex/tree/c10a12007999eb807f68cd9af9000fbaeab159cb/daggerverse/go/main.go#L28)
	if r.version != nil {
		return *r.version, nil
	}
	q := r.query.Select("version")

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// GoVetOpts contains options for Go.Vet
type GoVetOpts struct {

	// Default: "./..."
	Pkg string // go (https://github.com/z5labs/devex/tree/c10a12007999eb807f68cd9af9000fbaeab159cb/daggerverse/go/main.go#L475)
}

// Vet runs `go vet pkg` against the supplied source. pkg defaults to
// `./...`. Returns a non-nil error when vet reports any issue.
func (r *Go) Vet(ctx context.Context, source *Directory, opts ...GoVetOpts) error { // go (https://github.com/z5labs/devex/tree/c10a12007999eb807f68cd9af9000fbaeab159cb/daggerverse/go/main.go#L471)
	assertNotNil("source", source)
	if r.vet != nil {
		return nil
	}
	q := r.query.Select("vet")
	for i := len(opts) - 1; i >= 0; i-- {
		// `pkg` optional argument
		if !querybuilder.IsZeroValue(opts[i].Pkg) {
			q = q.Arg("pkg", opts[i].Pkg)
		}
	}
	q = q.Arg("source", source)

	return q.Execute(ctx)
}

// GoWorkOpts contains options for Go.Work
type GoWorkOpts struct {
	Args []string // go (https://github.com/z5labs/devex/tree/c10a12007999eb807f68cd9af9000fbaeab159cb/daggerverse/go/main.go#L133)
}

// Work runs `go work <subcommand> [args...]` against the supplied source
// and returns stdout. subcommand is required (e.g. "init", "use", "sync",
// "version").
func (r *Go) Work(ctx context.Context, source *Directory, subcommand string, opts ...GoWorkOpts) (string, error) { // go (https://github.com/z5labs/devex/tree/c10a12007999eb807f68cd9af9000fbaeab159cb/daggerverse/go/main.go#L128)
	assertNotNil("source", source)
	if r.work != nil {
		return *r.work, nil
	}
	q := r.query.Select("work")
	for i := len(opts) - 1; i >= 0; i-- {
		// `args` optional argument
		if !querybuilder.IsZeroValue(opts[i].Args) {
			q = q.Arg("args", opts[i].Args)
		}
	}
	q = q.Arg("source", source)
	q = q.Arg("subcommand", subcommand)

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// AsNode returns this Go as a Node.
// This is a local type conversion — no GraphQL call.
func (r *Go) AsNode() Node {
	return &NodeClient{
		query: r.query,
	}
}

// Ci is a chained builder for a standardized Go CI pipeline. Construct via
// Go.Ci(source); enable stages via the With* methods; call Run to execute
// checks-then-build, or Check to run only the parallel checks.
//
// Stage 1 runs the enabled static checks in parallel (Fmt, Vet, Lint, Test);
// errors are aggregated. Stage 2 builds the source and Run returns the
// produced binary as a *dagger.File. Downstream consumers compose that file
// into their own pipelines (package, sign, publish, ...).
type GoCi struct { // go (https://github.com/z5labs/devex/tree/c10a12007999eb807f68cd9af9000fbaeab159cb/daggerverse/go/ci.go#L44)
	query *querybuilder.Selection

	check *Void
	id    *ID
}
type WithGoCiFunc func(r *GoCi) *GoCi

// With calls the provided function with current GoCi.
//
// This is useful for reusability and readability by not breaking the calling chain.
func (r *GoCi) With(f WithGoCiFunc) *GoCi {
	return f(r)
}

func (r *GoCi) WithGraphQLQuery(q *querybuilder.Selection) *GoCi {
	return &GoCi{
		query: q,
	}
}

// Check runs the enabled check stages (Fmt, Vet, Lint, Test) in
// parallel via github.com/dagger/dagger/util/parallel and returns the
// aggregated error. Use when callers want to run the checks
// independently of the build (for example multi-platform pipelines
// that share one check run across N platform builds).
func (r *GoCi) Check(ctx context.Context) error { // go (https://github.com/z5labs/devex/tree/c10a12007999eb807f68cd9af9000fbaeab159cb/daggerverse/go/ci.go#L148)
	if r.check != nil {
		return nil
	}
	q := r.query.Select("check")

	return q.Execute(ctx)
}

// A unique identifier for this GoCi.
func (r *GoCi) ID(ctx context.Context) (ID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response ID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *GoCi) XXX_GraphQLType() string {
	return "GoCi"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *GoCi) XXX_GraphQLIDType() string {
	return "ID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *GoCi) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *GoCi) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *GoCi) UnmarshalJSON(bs []byte) error {
	var id string
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = GoCi{query: selectNode(dag.query, id, "GoCi")}
	return nil
}

// Run executes the pipeline: stage 1 (Check) → stage 2 (build). Returns
// the built binary as a *dagger.File. On stage-1 failure, returns the
// aggregated error from Check and a nil file (stage 2 is skipped).
func (r *GoCi) Run() *File { // go (https://github.com/z5labs/devex/tree/c10a12007999eb807f68cd9af9000fbaeab159cb/daggerverse/go/ci.go#L173)
	q := r.query.Select("run")

	return &File{
		query: q,
	}
}

// GoCiWithBuildOpts contains options for GoCi.WithBuild
type GoCiWithBuildOpts struct {
	Pkg string // go (https://github.com/z5labs/devex/tree/c10a12007999eb807f68cd9af9000fbaeab159cb/daggerverse/go/ci.go#L131)

	BinaryName string // go (https://github.com/z5labs/devex/tree/c10a12007999eb807f68cd9af9000fbaeab159cb/daggerverse/go/ci.go#L133)
}

// WithBuild configures the build stage parameters. pkg defaults to "."
// when empty; binaryName defaults to the basename of the `module` directive
// in go.mod when empty. Build is always executed by Run regardless of
// whether this method is called.
//
// Note: the binary-name flag is called binaryName (CLI: --binary-name) to
// avoid colliding with Dagger CLI's top-level --output/-o flag.
func (r *GoCi) WithBuild(opts ...GoCiWithBuildOpts) *GoCi { // go (https://github.com/z5labs/devex/tree/c10a12007999eb807f68cd9af9000fbaeab159cb/daggerverse/go/ci.go#L129)
	q := r.query.Select("withBuild")
	for i := len(opts) - 1; i >= 0; i-- {
		// `pkg` optional argument
		if !querybuilder.IsZeroValue(opts[i].Pkg) {
			q = q.Arg("pkg", opts[i].Pkg)
		}
		// `binaryName` optional argument
		if !querybuilder.IsZeroValue(opts[i].BinaryName) {
			q = q.Arg("binaryName", opts[i].BinaryName)
		}
	}

	return &GoCi{
		query: q,
	}
}

// WithFmt enables the gofmt check stage.
func (r *GoCi) WithFmt() *GoCi { // go (https://github.com/z5labs/devex/tree/c10a12007999eb807f68cd9af9000fbaeab159cb/daggerverse/go/ci.go#L77)
	q := r.query.Select("withFmt")

	return &GoCi{
		query: q,
	}
}

// GoCiWithLintOpts contains options for GoCi.WithLint
type GoCiWithLintOpts struct {
	Version string // go (https://github.com/z5labs/devex/tree/c10a12007999eb807f68cd9af9000fbaeab159cb/daggerverse/go/ci.go#L101)

	Config *File // go (https://github.com/z5labs/devex/tree/c10a12007999eb807f68cd9af9000fbaeab159cb/daggerverse/go/ci.go#L103)
}

// WithLint enables the golangci-lint check stage. version pins the
// installed golangci-lint version (defaults to defaultGolangciLintVersion
// when empty). config, if non-nil, is mounted at golangciLintConfigMountPath
// and passed to golangci-lint via --config.
//
// The default is a golangci-lint **v2** release, so a config passed here
// must be written in the v2 dialect — a file opening with `version: "2"`.
// A v1 file is not tolerated by a v2 binary; it is rejected before any
// linter runs. Pass a `v1.x` version to roll the whole stage back, config
// dialect included; the module path installed follows the version's major,
// so both majors are reachable without forking this pipeline.
func (r *GoCi) WithLint(opts ...GoCiWithLintOpts) *GoCi { // go (https://github.com/z5labs/devex/tree/c10a12007999eb807f68cd9af9000fbaeab159cb/daggerverse/go/ci.go#L99)
	q := r.query.Select("withLint")
	for i := len(opts) - 1; i >= 0; i-- {
		// `version` optional argument
		if !querybuilder.IsZeroValue(opts[i].Version) {
			q = q.Arg("version", opts[i].Version)
		}
		// `config` optional argument
		if !querybuilder.IsZeroValue(opts[i].Config) {
			q = q.Arg("config", opts[i].Config)
		}
	}

	return &GoCi{
		query: q,
	}
}

// GoCiWithTestOpts contains options for GoCi.WithTest
type GoCiWithTestOpts struct {
	Race bool // go (https://github.com/z5labs/devex/tree/c10a12007999eb807f68cd9af9000fbaeab159cb/daggerverse/go/ci.go#L115)
}

// WithTest enables the `go test ./...` check stage. Pass race=true to
// enable the data-race detector.
func (r *GoCi) WithTest(opts ...GoCiWithTestOpts) *GoCi { // go (https://github.com/z5labs/devex/tree/c10a12007999eb807f68cd9af9000fbaeab159cb/daggerverse/go/ci.go#L113)
	q := r.query.Select("withTest")
	for i := len(opts) - 1; i >= 0; i-- {
		// `race` optional argument
		if !querybuilder.IsZeroValue(opts[i].Race) {
			q = q.Arg("race", opts[i].Race)
		}
	}

	return &GoCi{
		query: q,
	}
}

// WithVet enables the `go vet ./...` check stage.
func (r *GoCi) WithVet() *GoCi { // go (https://github.com/z5labs/devex/tree/c10a12007999eb807f68cd9af9000fbaeab159cb/daggerverse/go/ci.go#L83)
	q := r.query.Select("withVet")

	return &GoCi{
		query: q,
	}
}

// AsNode returns this GoCi as a Node.
// This is a local type conversion — no GraphQL call.
func (r *GoCi) AsNode() Node {
	return &NodeClient{
		query: r.query,
	}
}

// GoOpts contains options for Query.Go
type GoOpts struct {
	Version string // go (https://github.com/z5labs/devex/tree/c10a12007999eb807f68cd9af9000fbaeab159cb/daggerverse/go/main.go#L37)
}

// New returns a Go module configured for the given toolchain version.
// version is optional: empty means the version is inferred from the source's
// go.mod for source-bearing CLI funcs, and "latest" is used for source-less
// funcs (Env, ToolVersion, Install).
func (r *Query) Go(opts ...GoOpts) *Go { // go (https://github.com/z5labs/devex/tree/c10a12007999eb807f68cd9af9000fbaeab159cb/daggerverse/go/main.go#L35)
	q := r.query.Select("go")
	for i := len(opts) - 1; i >= 0; i-- {
		// `version` optional argument
		if !querybuilder.IsZeroValue(opts[i].Version) {
			q = q.Arg("version", opts[i].Version)
		}
	}

	return &Go{
		query: q,
	}
}

// BuildMode is what `go build -buildmode` produces: the kind of artifact the
// linker emits, which for most of these is not an executable at all. It is an
// enum rather than a string because the set is closed and each member has a
// different output shape a caller has to be ready for.
//
// Two of `go build`'s modes are deliberately absent. `default` is what
// omitting this input already means, so a member for it would be a second
// spelling of the same request. `shared` is only half a feature without a
// `-linkshared` counterpart on the consuming build, which Build does not have
// — use Container() if you are building a shared std.
//
// Note on rendered names: the Dagger Go SDK derives each GraphQL enum member
// from the *constant identifier* in SCREAMING_SNAKE_CASE, so these surface as
// `ARCHIVE`, `C_ARCHIVE`, `C_SHARED`, `EXE`, `PIE` and `PLUGIN`. That is why
// the `go build` spelling (`c-archive`) lives in buildModeFlags below rather
// than in the identifier: a hyphen cannot appear in a Go identifier, so the
// mapping has to be explicit.
type GoBuildMode string // go (https://github.com/z5labs/devex/tree/c10a12007999eb807f68cd9af9000fbaeab159cb/daggerverse/go/buildmode.go#L31)

func (GoBuildMode) IsEnum() {}

func (v GoBuildMode) Name() string {
	switch v {
	case GoBuildModeArchive:
		return "ARCHIVE"
	case GoBuildModeCArchive:
		return "C_ARCHIVE"
	case GoBuildModeCShared:
		return "C_SHARED"
	case GoBuildModeExe:
		return "EXE"
	case GoBuildModePie:
		return "PIE"
	case GoBuildModePlugin:
		return "PLUGIN"
	default:
		return ""
	}
}

func (v GoBuildMode) Value() string {
	return string(v)
}

func (v *GoBuildMode) MarshalJSON() ([]byte, error) {
	if *v == "" {
		return []byte(`""`), nil
	}
	name := v.Name()
	if name == "" {
		return nil, fmt.Errorf("invalid enum value %q", *v)
	}
	return json.Marshal(name)
}

func (v *GoBuildMode) UnmarshalJSON(dt []byte) error {
	var s string
	if err := json.Unmarshal(dt, &s); err != nil {
		return err
	}
	switch s {
	case "":
		*v = ""
	case "ARCHIVE":
		*v = GoBuildModeArchive
	case "C_ARCHIVE":
		*v = GoBuildModeCArchive
	case "C_SHARED":
		*v = GoBuildModeCShared
	case "EXE":
		*v = GoBuildModeExe
	case "PIE":
		*v = GoBuildModePie
	case "PLUGIN":
		*v = GoBuildModePlugin
	default:
		return fmt.Errorf("invalid enum value %q", s)
	}
	return nil
}

const (
	// BuildModeArchive builds the listed non-main packages into `.a` files
	// (`archive`). Main packages are ignored, so pointing this at one
	// produces nothing.
	GoBuildModeArchive GoBuildMode = "ARCHIVE" // go (https://github.com/z5labs/devex/tree/c10a12007999eb807f68cd9af9000fbaeab159cb/daggerverse/go/buildmode.go#L37)

	// BuildModeCArchive builds the listed main package into a C archive
	// (`c-archive`). Only the functions carrying a cgo `//export` comment are
	// callable, and it is those exports rather than the mode that need cgo —
	// so this is not rejected alongside disableCgo the way race is. With cgo
	// off, a package whose exports live in cgo files fails to build at all
	// (`build constraints exclude all Go files`), and a pure-Go main package
	// still produces an archive, but one exporting nothing and carrying no
	// generated header. The archive/header pair is a consequence of having
	// cgo exports, not of asking for this mode.
	GoBuildModeCArchive GoBuildMode = "C_ARCHIVE" // go (https://github.com/z5labs/devex/tree/c10a12007999eb807f68cd9af9000fbaeab159cb/daggerverse/go/buildmode.go#L47)

	// BuildModeCShared builds the listed main package into a C shared
	// library (`c-shared`) — the same exported surface as C_ARCHIVE, linked
	// dynamically instead, and with the same relationship to cgo.
	GoBuildModeCShared GoBuildMode = "C_SHARED" // go (https://github.com/z5labs/devex/tree/c10a12007999eb807f68cd9af9000fbaeab159cb/daggerverse/go/buildmode.go#L51)

	// BuildModeExe builds the listed main packages into executables
	// (`exe`), forcing a position-dependent executable on a toolchain whose
	// default for the target is PIE.
	GoBuildModeExe GoBuildMode = "EXE" // go (https://github.com/z5labs/devex/tree/c10a12007999eb807f68cd9af9000fbaeab159cb/daggerverse/go/buildmode.go#L55)

	// BuildModePie builds the listed main packages into position
	// independent executables (`pie`), which is what a hardened runtime
	// wanting ASLR requires.
	GoBuildModePie GoBuildMode = "PIE" // go (https://github.com/z5labs/devex/tree/c10a12007999eb807f68cd9af9000fbaeab159cb/daggerverse/go/buildmode.go#L59)

	// BuildModePlugin builds the listed main packages into a shared library
	// loadable at run time with `plugin.Open` (`plugin`). The plugin and
	// its host have to be built by the same toolchain from the same
	// dependency versions or the load fails.
	GoBuildModePlugin GoBuildMode = "PLUGIN" // go (https://github.com/z5labs/devex/tree/c10a12007999eb807f68cd9af9000fbaeab159cb/daggerverse/go/buildmode.go#L64)

)
